declare module "eslint-plugin-react";
declare module "eslint-plugin-react-hooks";
declare module "eslint-plugin-react-refresh";
declare module "eslint-plugin-jsx-a11y";
declare module "@next/eslint-plugin-next";
declare module "eslint-plugin-tailwindcss";
declare module "eslint-plugin-markdown";
declare module "eslint-plugin-prettier";
declare module "eslint-config-prettier";
